import type { IFileWriter } from '../interfaces/file-writer.js';
import type { IServicePlugin, CLICommand } from '../interfaces/service-plugin.js';
import type { ProjectConfig } from '../models/project-config.js';
import { join } from 'path';

/**
 * CLIBuilder generates the bash CLI tool for managing the Docker project
 */
export class CLIBuilder {
  constructor(private fileWriter: IFileWriter) {}

  /**
   * Builds the complete CLI tool
   */
  async buildCLI(config: ProjectConfig, plugins: IServicePlugin[]): Promise<void> {
    const { outputPath, projectName } = config;
    const cliDir = join(outputPath, 'bin/cli');
    const commandsDir = join(cliDir, 'commands');

    // Build main CLI entry point
    await this.buildMainCLI(outputPath, projectName);

    // Build common utility functions
    await this.buildCommonUtilities(cliDir);

    // Build standard commands
    await this.buildStandardCommands(commandsDir, config);

    // Build plugin-specific commands
    await this.buildPluginCommands(commandsDir, config, plugins);
  }

  /**
   * Builds the main CLI entry point (e.g., ./myapp)
   */
  private async buildMainCLI(outputPath: string, projectName: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# ${projectName} CLI Tool
# Generated by Docker Project Builder

set -e

# Get script directory
SCRIPT_DIR="\$( cd "\$( dirname "\${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="\${SCRIPT_DIR}"

# Source common utilities
source "\${SCRIPT_DIR}/bin/cli/common.sh"

# Command dispatcher
COMMAND="\${1:-help}"
shift || true

case "\${COMMAND}" in
    up)
        source "\${SCRIPT_DIR}/bin/cli/commands/up.sh"
        ;;
    down)
        source "\${SCRIPT_DIR}/bin/cli/commands/down.sh"
        ;;
    build)
        source "\${SCRIPT_DIR}/bin/cli/commands/build.sh"
        ;;
    logs)
        source "\${SCRIPT_DIR}/bin/cli/commands/logs.sh"
        ;;
    exec)
        source "\${SCRIPT_DIR}/bin/cli/commands/exec.sh"
        ;;
    shell)
        source "\${SCRIPT_DIR}/bin/cli/commands/shell.sh"
        ;;
    status)
        source "\${SCRIPT_DIR}/bin/cli/commands/status.sh"
        ;;
    restart)
        source "\${SCRIPT_DIR}/bin/cli/commands/restart.sh"
        ;;
    help|--help|-h)
        show_help
        ;;
    *)
        error "Unknown command: \${COMMAND}"
        echo ""
        show_help
        exit 1
        ;;
esac

show_help() {
    cat << EOF
${projectName} CLI - Docker Project Management Tool

Usage: ./${projectName} [command] [options]

Commands:
    up          Start all containers
    down        Stop all containers
    build       Build or rebuild containers
    logs        View container logs
    exec        Execute a command in a container
    shell       Open a shell in a container
    status      Show container status
    restart     Restart containers
    help        Show this help message

Examples:
    ./${projectName} up
    ./${projectName} logs api
    ./${projectName} shell nextjs
    ./${projectName} exec api npm install

EOF
}
`;

    const filePath = join(outputPath, projectName);
    await this.fileWriter.writeFile(filePath, content);
    await this.fileWriter.makeExecutable(filePath);
  }

  /**
   * Builds common utility functions used by all commands
   */
  private async buildCommonUtilities(cliDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Common utilities for CLI commands

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

# Logging functions
info() {
    echo -e "\${BLUE}ℹ\${NC} $*"
}

success() {
    echo -e "\${GREEN}✓\${NC} $*"
}

warning() {
    echo -e "\${YELLOW}⚠\${NC} $*"
}

error() {
    echo -e "\${RED}✗\${NC} $*" >&2
}

# Docker Compose wrapper
dc() {
    # Load base compose and override if it exists
    local compose_files="-f \${PROJECT_ROOT}/docker/compose/docker-compose.yml"
    if [ -f "\${PROJECT_ROOT}/docker/compose/docker-compose.override.yml" ]; then
        compose_files="$compose_files -f \${PROJECT_ROOT}/docker/compose/docker-compose.override.yml"
    fi
    docker compose $compose_files "$@"
}

# Check if docker is running
check_docker() {
    if ! docker info > /dev/null 2>&1; then
        error "Docker is not running. Please start Docker and try again."
        exit 1
    fi
}

# Load environment variables
load_env() {
    if [ -f "\${PROJECT_ROOT}/.env" ]; then
        set -a
        source "\${PROJECT_ROOT}/.env"
        set +a
    else
        warning ".env file not found. Using defaults."
    fi
}

# Get list of service names
get_services() {
    dc config --services
}

# Check if service exists
service_exists() {
    local service="$1"
    get_services | grep -q "^\${service}$"
}
`;

    const filePath = join(cliDir, 'common.sh');
    await this.fileWriter.writeFile(filePath, content);
  }

  /**
   * Builds standard CLI commands (up, down, build, logs, etc.)
   */
  private async buildStandardCommands(commandsDir: string, config: ProjectConfig): Promise<void> {
    // up command
    await this.buildUpCommand(commandsDir);

    // down command
    await this.buildDownCommand(commandsDir);

    // build command
    await this.buildBuildCommand(commandsDir);

    // logs command
    await this.buildLogsCommand(commandsDir);

    // exec command
    await this.buildExecCommand(commandsDir);

    // shell command
    await this.buildShellCommand(commandsDir);

    // status command
    await this.buildStatusCommand(commandsDir);

    // restart command
    await this.buildRestartCommand(commandsDir);
  }

  /**
   * Builds the 'up' command
   */
  private async buildUpCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Start all containers

check_docker
load_env

info "Starting containers..."
dc up -d "$@"

success "Containers started successfully!"
info "Run './\${PROJECT_NAME} status' to see container status"
info "Run './\${PROJECT_NAME} logs' to view logs"
`;

    await this.fileWriter.writeFile(join(commandsDir, 'up.sh'), content);
  }

  /**
   * Builds the 'down' command
   */
  private async buildDownCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Stop all containers

check_docker

info "Stopping containers..."
dc down "$@"

success "Containers stopped successfully!"
`;

    await this.fileWriter.writeFile(join(commandsDir, 'down.sh'), content);
  }

  /**
   * Builds the 'build' command
   */
  private async buildBuildCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Build or rebuild containers

check_docker
load_env

SERVICE="\${1:-}"

if [ -n "\${SERVICE}" ]; then
    if service_exists "\${SERVICE}"; then
        info "Building \${SERVICE}..."
        dc build "\${SERVICE}"
        success "\${SERVICE} built successfully!"
    else
        error "Service '\${SERVICE}' not found"
        exit 1
    fi
else
    info "Building all containers..."
    dc build
    success "All containers built successfully!"
fi
`;

    await this.fileWriter.writeFile(join(commandsDir, 'build.sh'), content);
  }

  /**
   * Builds the 'logs' command
   */
  private async buildLogsCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# View container logs

check_docker

SERVICE="\${1:-}"
FOLLOW="\${2:-}"

if [ "\${FOLLOW}" = "-f" ] || [ "\${FOLLOW}" = "--follow" ]; then
    FOLLOW_FLAG="-f"
else
    FOLLOW_FLAG=""
fi

if [ -n "\${SERVICE}" ]; then
    if service_exists "\${SERVICE}"; then
        dc logs \${FOLLOW_FLAG} "\${SERVICE}"
    else
        error "Service '\${SERVICE}' not found"
        exit 1
    fi
else
    dc logs \${FOLLOW_FLAG}
fi
`;

    await this.fileWriter.writeFile(join(commandsDir, 'logs.sh'), content);
  }

  /**
   * Builds the 'exec' command
   */
  private async buildExecCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Execute a command in a container

check_docker

SERVICE="\${1:-}"
shift || true

if [ -z "\${SERVICE}" ]; then
    error "Service name required"
    echo "Usage: exec <service> <command>"
    exit 1
fi

if ! service_exists "\${SERVICE}"; then
    error "Service '\${SERVICE}' not found"
    exit 1
fi

dc exec "\${SERVICE}" "$@"
`;

    await this.fileWriter.writeFile(join(commandsDir, 'exec.sh'), content);
  }

  /**
   * Builds the 'shell' command
   */
  private async buildShellCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Open a shell in a container

check_docker

SERVICE="\${1:-}"

if [ -z "\${SERVICE}" ]; then
    error "Service name required"
    echo "Usage: shell <service>"
    exit 1
fi

if ! service_exists "\${SERVICE}"; then
    error "Service '\${SERVICE}' not found"
    exit 1
fi

info "Opening shell in \${SERVICE}..."

# Try bash first, fallback to sh
if dc exec "\${SERVICE}" bash --version > /dev/null 2>&1; then
    dc exec "\${SERVICE}" bash
else
    dc exec "\${SERVICE}" sh
fi
`;

    await this.fileWriter.writeFile(join(commandsDir, 'shell.sh'), content);
  }

  /**
   * Builds the 'status' command
   */
  private async buildStatusCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Show container status

check_docker

info "Container Status:"
echo ""
dc ps
`;

    await this.fileWriter.writeFile(join(commandsDir, 'status.sh'), content);
  }

  /**
   * Builds the 'restart' command
   */
  private async buildRestartCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Restart containers

check_docker

SERVICE="\${1:-}"

if [ -n "\${SERVICE}" ]; then
    if service_exists "\${SERVICE}"; then
        info "Restarting \${SERVICE}..."
        dc restart "\${SERVICE}"
        success "\${SERVICE} restarted successfully!"
    else
        error "Service '\${SERVICE}' not found"
        exit 1
    fi
else
    info "Restarting all containers..."
    dc restart
    success "All containers restarted successfully!"
fi
`;

    await this.fileWriter.writeFile(join(commandsDir, 'restart.sh'), content);
  }

  /**
   * Builds plugin-specific CLI commands
   */
  private async buildPluginCommands(
    commandsDir: string,
    config: ProjectConfig,
    plugins: IServicePlugin[]
  ): Promise<void> {
    for (const plugin of plugins) {
      const commands = plugin.getCLICommands(config);

      for (const command of commands) {
        const fileName = `${command.name}.sh`;
        const filePath = join(commandsDir, fileName);
        await this.fileWriter.writeFile(filePath, command.script);
      }
    }
  }
}
