import type { IFileWriter } from '../interfaces/file-writer.js';
import type { IServicePlugin, CLICommand } from '../interfaces/service-plugin.js';
import type { ProjectConfig } from '../models/project-config.js';
import { join } from 'path';

/**
 * CLIBuilder generates the bash CLI tool for managing the Docker project
 */
export class CLIBuilder {
  constructor(private fileWriter: IFileWriter) {}

  /**
   * Builds the complete CLI tool
   */
  async buildCLI(config: ProjectConfig, plugins: IServicePlugin[]): Promise<void> {
    const { outputPath, projectName } = config;
    const cliDir = join(outputPath, 'bin/cli');
    const commandsDir = join(cliDir, 'commands');

    // Build main CLI entry point
    await this.buildMainCLI(outputPath, projectName);

    // Build common utility functions
    await this.buildCommonUtilities(cliDir);

    // Build standard commands
    await this.buildStandardCommands(commandsDir, config);

    // Build plugin-specific commands
    await this.buildPluginCommands(commandsDir, config, plugins);
  }

  /**
   * Builds the main CLI entry point (./cli)
   */
  private async buildMainCLI(outputPath: string, projectName: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# ${projectName} CLI Tool
# Generated by Docker Project Builder

set -e

# Get script directory
SCRIPT_DIR="\$( cd "\$( dirname "\${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="\${SCRIPT_DIR}"

# Source common utilities
source "\${SCRIPT_DIR}/bin/cli/common.sh"

show_help() {
    cat << EOF
${projectName} CLI - Docker Project Management Tool

Usage: ./cli [command] [options]

Commands:
    up          Start all containers
    down        Stop and remove containers
    clean       Remove containers, volumes, and local images
    build       Build or rebuild containers
    logs        View container logs
    exec        Execute a command in a container
    shell       Open a shell in a container
    status      Show container status
    restart     Restart containers
    certs       Generate SSL certificates (self-signed or Let's Encrypt)
    certs-renew Renew Let's Encrypt certificates
    help        Show this help message

Examples:
    ./cli up
    ./cli logs api
    ./cli shell nextjs
    ./cli exec api npm install
    ./cli certs
    ./cli certs-renew

EOF
}

# Command dispatcher
COMMAND="\${1:-help}"
shift || true

case "\${COMMAND}" in
    up)
        source "\${SCRIPT_DIR}/bin/cli/commands/up.sh"
        ;;
    down)
        source "\${SCRIPT_DIR}/bin/cli/commands/down.sh"
        ;;
    clean)
        source "\${SCRIPT_DIR}/bin/cli/commands/clean.sh"
        ;;
    build)
        source "\${SCRIPT_DIR}/bin/cli/commands/build.sh"
        ;;
    logs)
        source "\${SCRIPT_DIR}/bin/cli/commands/logs.sh"
        ;;
    exec)
        source "\${SCRIPT_DIR}/bin/cli/commands/exec.sh"
        ;;
    shell)
        source "\${SCRIPT_DIR}/bin/cli/commands/shell.sh"
        ;;
    status)
        source "\${SCRIPT_DIR}/bin/cli/commands/status.sh"
        ;;
    restart)
        source "\${SCRIPT_DIR}/bin/cli/commands/restart.sh"
        ;;
    certs)
        source "\${SCRIPT_DIR}/bin/cli/commands/certs.sh"
        ;;
    certs-renew)
        source "\${SCRIPT_DIR}/bin/cli/commands/certs-renew.sh"
        ;;
    help|--help|-h)
        show_help
        ;;
    *)
        error "Unknown command: \${COMMAND}"
        echo ""
        show_help
        exit 1
        ;;
esac
`;

    const filePath = join(outputPath, 'cli');
    await this.fileWriter.writeFile(filePath, content);
    await this.fileWriter.makeExecutable(filePath);
  }

  /**
   * Builds common utility functions used by all commands
   */
  private async buildCommonUtilities(cliDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Common utilities for CLI commands

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

# Logging functions
info() {
    echo -e "\${BLUE}ℹ\${NC} $*"
}

success() {
    echo -e "\${GREEN}✓\${NC} $*"
}

warning() {
    echo -e "\${YELLOW}⚠\${NC} $*"
}

error() {
    echo -e "\${RED}✗\${NC} $*" >&2
}

# Docker Compose wrapper (environment-aware)
dc() {
    local compose_files="-f \${PROJECT_ROOT}/docker/compose/docker-compose.yml"

    # Determine environment from APP_ENV
    local env="\${APP_ENV:-local}"

    case "\${env}" in
        local)
            if [ -f "\${PROJECT_ROOT}/docker/compose/docker-compose.override.yml" ]; then
                compose_files="\$compose_files -f \${PROJECT_ROOT}/docker/compose/docker-compose.override.yml"
            fi
            ;;
        staging)
            if [ -f "\${PROJECT_ROOT}/docker/compose/docker-compose.staging.yml" ]; then
                compose_files="\$compose_files -f \${PROJECT_ROOT}/docker/compose/docker-compose.staging.yml"
            fi
            ;;
        prod)
            if [ -f "\${PROJECT_ROOT}/docker/compose/docker-compose.prod.yml" ]; then
                compose_files="\$compose_files -f \${PROJECT_ROOT}/docker/compose/docker-compose.prod.yml"
            fi
            ;;
    esac

    local env_file=""
    if [ -f "\${PROJECT_ROOT}/.env" ]; then
        env_file="--env-file \${PROJECT_ROOT}/.env"
    fi
    docker compose \$env_file \$compose_files "$@"
}

# Check if docker is running
check_docker() {
    if ! docker info > /dev/null 2>&1; then
        error "Docker is not running. Please start Docker and try again."
        exit 1
    fi
}

# Load environment variables
load_env() {
    if [ -f "\${PROJECT_ROOT}/.env" ]; then
        set -a
        source "\${PROJECT_ROOT}/.env"
        set +a
    else
        warning ".env file not found. Using defaults."
    fi
}

# Get list of service names
get_services() {
    dc config --services
}

# Check if service exists
service_exists() {
    local service="$1"
    get_services | grep -q "^\${service}$"
}
`;

    const filePath = join(cliDir, 'common.sh');
    await this.fileWriter.writeFile(filePath, content);
  }

  /**
   * Builds standard CLI commands (up, down, build, logs, etc.)
   */
  private async buildStandardCommands(commandsDir: string, config: ProjectConfig): Promise<void> {
    // up command
    await this.buildUpCommand(commandsDir);

    // down command
    await this.buildDownCommand(commandsDir);

    // clean command
    await this.buildCleanCommand(commandsDir);

    // build command
    await this.buildBuildCommand(commandsDir);

    // logs command
    await this.buildLogsCommand(commandsDir);

    // exec command
    await this.buildExecCommand(commandsDir);

    // shell command
    await this.buildShellCommand(commandsDir);

    // status command
    await this.buildStatusCommand(commandsDir);

    // restart command
    await this.buildRestartCommand(commandsDir);

    // certs command
    await this.buildCertsCommand(commandsDir, config);

    // certs-renew command
    await this.buildCertsRenewCommand(commandsDir, config);
  }

  /**
   * Builds the 'up' command
   */
  private async buildUpCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Start all containers

check_docker
load_env

info "Starting containers..."
dc up -d "$@"

success "Containers started successfully!"
info "Run './cli status' to see container status"
info "Run './cli logs' to view logs"
`;

    await this.fileWriter.writeFile(join(commandsDir, 'up.sh'), content);
  }

  /**
   * Builds the 'down' command
   */
  private async buildDownCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Stop all containers

check_docker

info "Stopping containers..."
dc down "$@"

success "Containers stopped successfully!"
`;

    await this.fileWriter.writeFile(join(commandsDir, 'down.sh'), content);
  }

  /**
   * Builds the 'clean' command
   */
  private async buildCleanCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Remove all project containers, volumes, and local images

check_docker

info "Removing project containers, volumes, and images..."
dc down --volumes --rmi local "$@"

success "Project cleaned successfully!"
`;

    await this.fileWriter.writeFile(join(commandsDir, 'clean.sh'), content);
  }

  /**
   * Builds the 'build' command
   */
  private async buildBuildCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Build or rebuild containers

check_docker
load_env

SERVICE="\${1:-}"

if [ -n "\${SERVICE}" ]; then
    if service_exists "\${SERVICE}"; then
        info "Building \${SERVICE}..."
        dc build "\${SERVICE}"
        success "\${SERVICE} built successfully!"
    else
        error "Service '\${SERVICE}' not found"
        exit 1
    fi
else
    info "Building all containers..."
    dc build
    success "All containers built successfully!"
fi
`;

    await this.fileWriter.writeFile(join(commandsDir, 'build.sh'), content);
  }

  /**
   * Builds the 'logs' command
   */
  private async buildLogsCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# View container logs

check_docker

SERVICE="\${1:-}"
FOLLOW="\${2:-}"

if [ "\${FOLLOW}" = "-f" ] || [ "\${FOLLOW}" = "--follow" ]; then
    FOLLOW_FLAG="-f"
else
    FOLLOW_FLAG=""
fi

if [ -n "\${SERVICE}" ]; then
    if service_exists "\${SERVICE}"; then
        dc logs \${FOLLOW_FLAG} "\${SERVICE}"
    else
        error "Service '\${SERVICE}' not found"
        exit 1
    fi
else
    dc logs \${FOLLOW_FLAG}
fi
`;

    await this.fileWriter.writeFile(join(commandsDir, 'logs.sh'), content);
  }

  /**
   * Builds the 'exec' command
   */
  private async buildExecCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Execute a command in a container

check_docker

SERVICE="\${1:-}"
shift || true

if [ -z "\${SERVICE}" ]; then
    error "Service name required"
    echo "Usage: exec <service> <command>"
    exit 1
fi

if ! service_exists "\${SERVICE}"; then
    error "Service '\${SERVICE}' not found"
    exit 1
fi

dc exec "\${SERVICE}" "$@"
`;

    await this.fileWriter.writeFile(join(commandsDir, 'exec.sh'), content);
  }

  /**
   * Builds the 'shell' command
   */
  private async buildShellCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Open a shell in a container

check_docker

SERVICE="\${1:-}"

if [ -z "\${SERVICE}" ]; then
    error "Service name required"
    echo "Usage: shell <service>"
    exit 1
fi

if ! service_exists "\${SERVICE}"; then
    error "Service '\${SERVICE}' not found"
    exit 1
fi

info "Opening shell in \${SERVICE}..."

# Try bash first, fallback to sh
if dc exec "\${SERVICE}" bash --version > /dev/null 2>&1; then
    dc exec "\${SERVICE}" bash
else
    dc exec "\${SERVICE}" sh
fi
`;

    await this.fileWriter.writeFile(join(commandsDir, 'shell.sh'), content);
  }

  /**
   * Builds the 'status' command
   */
  private async buildStatusCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Show container status

check_docker

info "Container Status:"
echo ""
dc ps
`;

    await this.fileWriter.writeFile(join(commandsDir, 'status.sh'), content);
  }

  /**
   * Builds the 'restart' command
   */
  private async buildRestartCommand(commandsDir: string): Promise<void> {
    const content = `#!/usr/bin/env bash

# Restart containers

check_docker

SERVICE="\${1:-}"

if [ -n "\${SERVICE}" ]; then
    if service_exists "\${SERVICE}"; then
        info "Restarting \${SERVICE}..."
        dc restart "\${SERVICE}"
        success "\${SERVICE} restarted successfully!"
    else
        error "Service '\${SERVICE}' not found"
        exit 1
    fi
else
    info "Restarting all containers..."
    dc restart
    success "All containers restarted successfully!"
fi
`;

    await this.fileWriter.writeFile(join(commandsDir, 'restart.sh'), content);
  }

  /**
   * Builds the 'certs' command
   */
  private async buildCertsCommand(commandsDir: string, config: ProjectConfig): Promise<void> {
    const content = `#!/usr/bin/env bash

# SSL Certificate management command
# Usage: ./cli certs [--domain=<domain>] [--days=<days>] [--force] [--email=<email>] [--staging-le]

# ============================================================================
# Help
# ============================================================================

show_cert_help() {
    echo "Generate SSL Certificates"
    echo ""
    echo "Usage:"
    echo "  ./cli certs [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --domain=<domain>  Domain to generate cert for (default: ${config.domain})"
    echo "  --days=<days>      Certificate validity in days (default: 365, local only)"
    echo "  --force            Regenerate existing certificates"
    echo "  --email=<email>    Email for Let's Encrypt registration (staging/prod)"
    echo "  --staging-le       Use Let's Encrypt staging server (for testing)"
    echo "  -h, --help         Show this help message"
    echo ""
    echo "Behavior by environment (APP_ENV):"
    echo "  local              Self-signed CA + domain certificate (openssl)"
    echo "  staging/prod       Let's Encrypt certificate via certbot"
    echo ""
    echo "Examples:"
    echo "  ./cli certs                                   # Local: self-signed for ${config.domain}"
    echo "  ./cli certs --force                           # Regenerate certificates"
    echo "  ./cli certs --email=admin@example.com         # Staging/Prod: Let's Encrypt"
    echo "  ./cli certs --staging-le                      # Test with LE staging server"
    echo ""
    echo "Notes:"
    echo "  - Local: Creates a CA and signs domain certs. macOS Keychain trust optional."
    echo "  - Staging/Prod: Uses certbot with HTTP-01 challenge (proxy must be running)."
    echo "  - After generating, rebuild proxy: ./cli build proxy && ./cli restart proxy"
    echo ""
}

# ============================================================================
# Parse Arguments
# ============================================================================

load_env

DOMAIN="\${DOMAIN:-${config.domain}}"
DAYS="365"
FORCE=""
EMAIL="\${CERT_EMAIL:-admin@\${DOMAIN}}"
LE_STAGING=""

while [[ \$# -gt 0 ]]; do
    case \$1 in
        --domain=*)
            DOMAIN="\${1#*=}"
            shift
            ;;
        --days=*)
            DAYS="\${1#*=}"
            shift
            ;;
        --force)
            FORCE="true"
            shift
            ;;
        --email=*)
            EMAIL="\${1#*=}"
            shift
            ;;
        --staging-le)
            LE_STAGING="true"
            shift
            ;;
        -h|--help)
            show_cert_help
            exit 0
            ;;
        *)
            error "Unknown option: \$1"
            show_cert_help
            exit 1
            ;;
    esac
done

SSL_DIR="\${PROJECT_ROOT}/docker/ssl"
ENV="\${APP_ENV:-local}"

mkdir -p "\${SSL_DIR}"

# ============================================================================
# Local: Self-signed CA + Domain Certificate
# ============================================================================

generate_self_signed() {
    # Check if openssl is available
    if ! command -v openssl &> /dev/null; then
        error "openssl is not installed. Please install it and try again."
        exit 1
    fi

    CA_KEY="\${SSL_DIR}/ca.key"
    CA_CERT="\${SSL_DIR}/ca.crt"

    # Step 1: Create local Certificate Authority (CA)
    if [ -f "\${CA_KEY}" ] && [ -f "\${CA_CERT}" ] && [ -z "\${FORCE}" ]; then
        info "Using existing Certificate Authority"
    else
        info "Creating local Certificate Authority..."

        openssl genrsa -out "\${CA_KEY}" 4096 2>/dev/null

        openssl req -x509 -new -nodes \\
            -key "\${CA_KEY}" \\
            -sha256 \\
            -days 1825 \\
            -out "\${CA_CERT}" \\
            -subj "/C=US/ST=Local/L=Local/O=${config.projectName} Dev CA/CN=${config.projectName} Local CA"

        if [ \$? -ne 0 ]; then
            error "Failed to create Certificate Authority."
            exit 1
        fi

        success "Certificate Authority created"
    fi

    # Step 2: Generate domain certificate signed by our CA
    DOMAIN_KEY="\${SSL_DIR}/\${DOMAIN}.key"
    DOMAIN_CERT="\${SSL_DIR}/\${DOMAIN}.crt"
    DOMAIN_CSR="\${SSL_DIR}/\${DOMAIN}.csr"
    DOMAIN_EXT="\${SSL_DIR}/\${DOMAIN}.ext"

    if [ -f "\${DOMAIN_KEY}" ] && [ -f "\${DOMAIN_CERT}" ] && [ -z "\${FORCE}" ]; then
        warning "Certificate for \${DOMAIN} already exists. Use --force to regenerate."
        exit 0
    fi

    info "Generating certificate for \${DOMAIN}..."

    openssl genrsa -out "\${DOMAIN_KEY}" 2048 2>/dev/null

    openssl req -new \\
        -key "\${DOMAIN_KEY}" \\
        -out "\${DOMAIN_CSR}" \\
        -subj "/C=US/ST=Local/L=Local/O=${config.projectName}/CN=\${DOMAIN}"

    cat > "\${DOMAIN_EXT}" << EXTEOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = \${DOMAIN}
DNS.2 = *.\${DOMAIN}
DNS.3 = localhost
IP.1 = 127.0.0.1
EXTEOF

    openssl x509 -req \\
        -in "\${DOMAIN_CSR}" \\
        -CA "\${CA_CERT}" \\
        -CAkey "\${CA_KEY}" \\
        -CAcreateserial \\
        -out "\${DOMAIN_CERT}" \\
        -days "\${DAYS}" \\
        -sha256 \\
        -extfile "\${DOMAIN_EXT}" 2>/dev/null

    if [ \$? -ne 0 ]; then
        error "Failed to generate domain certificate."
        exit 1
    fi

    rm -f "\${DOMAIN_CSR}" "\${DOMAIN_EXT}" "\${SSL_DIR}/ca.srl"

    success "SSL certificate generated for \${DOMAIN}"
    echo ""
    info "CA Certificate:     \${CA_CERT}"
    info "Domain Certificate: \${DOMAIN_CERT}"
    info "Domain Private Key: \${DOMAIN_KEY}"
    echo ""

    # macOS Keychain trust (optional)
    if [[ "\$(uname)" == "Darwin" ]]; then
        echo ""
        read -p "Add CA to macOS Keychain for browser trust? [y/N] " -n 1 -r
        echo ""
        if [[ \$REPLY =~ ^[Yy]$ ]]; then
            info "Adding CA certificate to macOS Keychain (requires sudo)..."
            sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "\${CA_CERT}"
            if [ \$? -eq 0 ]; then
                success "CA added to Keychain. Browsers will trust \${DOMAIN} certificates."
            else
                warning "Failed to add CA to Keychain. You can do it manually:"
                echo "  sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain \${CA_CERT}"
            fi
        else
            info "Skipping Keychain trust. To manually trust later:"
            echo "  sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain \${CA_CERT}"
        fi
    fi

    echo ""
    info "To apply certificates, rebuild and restart the proxy:"
    echo "  ./cli build proxy && ./cli restart proxy"
    echo ""
    warning "These are self-signed certificates for local development only."
}

# ============================================================================
# Staging/Prod: Let's Encrypt via Certbot
# ============================================================================

generate_letsencrypt() {
    check_docker

    # Verify proxy is running (needed for HTTP-01 challenge)
    if ! dc ps --format '{{.State}}' proxy 2>/dev/null | grep -qi "running"; then
        error "Proxy must be running for Let's Encrypt HTTP-01 challenge."
        info "Start the proxy first: ./cli up proxy"
        exit 1
    fi

    info "Requesting Let's Encrypt certificate for \${DOMAIN}..."

    # Build certbot arguments
    local certbot_args="certonly --webroot -w /var/www/certbot"
    certbot_args="\${certbot_args} --email \${EMAIL} --agree-tos --no-eff-email"
    certbot_args="\${certbot_args} -d \${DOMAIN}"

    # Use LE staging server for testing
    if [ -n "\${LE_STAGING}" ]; then
        certbot_args="\${certbot_args} --staging"
        warning "Using Let's Encrypt STAGING server (certs will NOT be trusted)"
    fi

    # Force renewal
    if [ -n "\${FORCE}" ]; then
        certbot_args="\${certbot_args} --force-renewal"
    fi

    # Create letsencrypt directory
    mkdir -p "\${SSL_DIR}/letsencrypt"

    # Run certbot via docker compose
    dc run --rm --profile certbot certbot \${certbot_args}

    if [ \$? -ne 0 ]; then
        error "Let's Encrypt certificate request failed."
        info "Make sure:"
        echo "  - Port 80 is accessible from the internet"
        echo "  - DNS for \${DOMAIN} points to this server"
        echo "  - Proxy is running: ./cli up proxy"
        exit 1
    fi

    # Copy certs to standard location for Apache
    local le_live="\${SSL_DIR}/letsencrypt/live/\${DOMAIN}"
    if [ -d "\${le_live}" ]; then
        cp -L "\${le_live}/fullchain.pem" "\${SSL_DIR}/\${DOMAIN}.crt"
        cp -L "\${le_live}/privkey.pem" "\${SSL_DIR}/\${DOMAIN}.key"
        cp -L "\${le_live}/chain.pem" "\${SSL_DIR}/ca.crt"
        success "Let's Encrypt certificates installed for \${DOMAIN}"
    else
        error "Let's Encrypt certificates not found at expected path."
        exit 1
    fi

    # Reload Apache to pick up new certs
    info "Reloading Apache..."
    dc exec proxy httpd -k graceful
    success "Apache reloaded with new certificates."

    echo ""
    info "Certificate: \${SSL_DIR}/\${DOMAIN}.crt"
    info "Private Key: \${SSL_DIR}/\${DOMAIN}.key"
    echo ""
    info "To renew certificates later: ./cli certs-renew"
    warning "Certificates expire in 90 days. Set up a cron job for automatic renewal."
}

# ============================================================================
# Execute based on environment
# ============================================================================

case "\${ENV}" in
    local)
        info "Environment: local (self-signed certificates)"
        generate_self_signed
        ;;
    staging|prod)
        info "Environment: \${ENV} (Let's Encrypt)"
        generate_letsencrypt
        ;;
    *)
        error "Unknown environment: \${ENV}"
        info "Set APP_ENV in your .env file to: local, staging, or prod"
        exit 1
        ;;
esac
`;

    await this.fileWriter.writeFile(join(commandsDir, 'certs.sh'), content);
  }

  /**
   * Builds the 'certs-renew' command
   */
  private async buildCertsRenewCommand(commandsDir: string, config: ProjectConfig): Promise<void> {
    const content = `#!/usr/bin/env bash

# Renew SSL certificates
# For Let's Encrypt (staging/prod) environments

load_env

ENV="\${APP_ENV:-local}"
DOMAIN="\${DOMAIN:-${config.domain}}"
SSL_DIR="\${PROJECT_ROOT}/docker/ssl"

if [ "\${ENV}" = "local" ]; then
    info "Local environment uses self-signed certificates."
    info "To regenerate, run: ./cli certs --force"
    exit 0
fi

check_docker

info "Renewing Let's Encrypt certificates..."

# Run certbot renew
dc run --rm --profile certbot certbot renew

if [ \$? -ne 0 ]; then
    error "Certificate renewal failed."
    exit 1
fi

# Copy renewed certs to standard location
LE_LIVE="\${SSL_DIR}/letsencrypt/live/\${DOMAIN}"
if [ -d "\${LE_LIVE}" ]; then
    cp -L "\${LE_LIVE}/fullchain.pem" "\${SSL_DIR}/\${DOMAIN}.crt"
    cp -L "\${LE_LIVE}/privkey.pem" "\${SSL_DIR}/\${DOMAIN}.key"
    cp -L "\${LE_LIVE}/chain.pem" "\${SSL_DIR}/ca.crt"
    success "Certificates renewed for \${DOMAIN}"
else
    warning "No renewed certificates found. They may not have been due for renewal."
fi

# Reload Apache
info "Reloading Apache..."
dc exec proxy httpd -k graceful
success "Apache reloaded."

echo ""
info "Tip: Add a cron job for automatic renewal:"
echo "  0 3 * * * cd \${PROJECT_ROOT} && ./cli certs-renew >> /var/log/cert-renew.log 2>&1"
`;

    await this.fileWriter.writeFile(join(commandsDir, 'certs-renew.sh'), content);
  }

  /**
   * Builds plugin-specific CLI commands
   */
  private async buildPluginCommands(
    commandsDir: string,
    config: ProjectConfig,
    plugins: IServicePlugin[]
  ): Promise<void> {
    for (const plugin of plugins) {
      const commands = plugin.getCLICommands(config);

      for (const command of commands) {
        const fileName = `${command.name}.sh`;
        const filePath = join(commandsDir, fileName);
        await this.fileWriter.writeFile(filePath, command.script);
      }
    }
  }
}
