import type { IFileWriter } from '../interfaces/file-writer.js';
import type { IServicePlugin, Environment, EnvVarBlock } from '../interfaces/service-plugin.js';
import type { ProjectConfig } from '../models/project-config.js';
import { join } from 'path';

/**
 * EnvBuilder generates .env files from plugin contributions
 */
export class EnvBuilder {
  constructor(private fileWriter: IFileWriter) {}

  /**
   * Builds all .env files for different environments
   */
  async buildEnvFiles(config: ProjectConfig, plugins: IServicePlugin[]): Promise<void> {
    const { outputPath } = config;

    // Build .env (local development)
    await this.buildEnvFile(outputPath, config, plugins, 'local', '.env');

    // Build .env.example (template)
    await this.buildEnvFile(outputPath, config, plugins, 'local', '.env.example');

    // Build .env.staging.example (staging template)
    if (config.environments.includes('staging')) {
      await this.buildEnvFile(outputPath, config, plugins, 'staging', '.env.staging.example');
    }

    // Build .env.production.example (production template)
    if (config.environments.includes('prod')) {
      await this.buildEnvFile(outputPath, config, plugins, 'prod', '.env.production.example');
    }
  }

  /**
   * Builds a single .env file for a specific environment
   */
  private async buildEnvFile(
    outputPath: string,
    config: ProjectConfig,
    plugins: IServicePlugin[],
    env: Environment,
    fileName: string
  ): Promise<void> {
    const sections: string[] = [];

    // Header
    sections.push(this.buildHeader(config, env));

    // Global config section
    sections.push(this.buildGlobalSection(config, env));

    // Collect env vars from all plugins
    for (const plugin of plugins) {
      const envVars = plugin.getEnvVars(config, env);
      if (envVars && Object.keys(envVars).length > 0) {
        sections.push(this.buildPluginSection(plugin, envVars));
      }
    }

    // Join sections with double newlines
    const content = sections.join('\n\n') + '\n';

    // Write file
    const filePath = join(outputPath, fileName);
    await this.fileWriter.writeFile(filePath, content);
  }

  /**
   * Builds the file header
   */
  private buildHeader(config: ProjectConfig, env: Environment): string {
    return [
      `# ${config.projectName} - ${env.toUpperCase()} Environment`,
      `# Generated by Docker Project Builder`,
      `# Do not commit this file to version control`,
    ].join('\n');
  }

  /**
   * Builds the global configuration section
   */
  private buildGlobalSection(config: ProjectConfig, env: Environment): string {
    const lines: string[] = [
      '# ===== Global Configuration =====',
      `APP_ENV=${env}`,
      `PROJECT_NAME=${config.projectName}`,
      `CONTAINER_PREFIX=${config.containerPrefix}`,
      `DOMAIN=${config.domain}`,
      `PROXY_PORT=${config.proxy.port}`,
      `PROXY_SSL_PORT=${config.proxy.sslPort}`,
      '',
      '# Docker Compose profiles (comma-separated: db,certbot,auto-renew,tools)',
      `COMPOSE_PROFILES=${env === 'local' ? 'local' : ''}`,
      '',
      '# Let\'s Encrypt certificate email (required for staging/prod SSL)',
      `CERT_EMAIL=${env === 'prod' || env === 'staging' ? 'admin@' + config.domain : ''}`,
    ];

    return lines.join('\n');
  }

  /**
   * Builds a section for a specific plugin's env vars
   */
  private buildPluginSection(plugin: IServicePlugin, envVars: EnvVarBlock): string {
    const lines: string[] = [
      `# ===== ${plugin.displayName} =====`,
    ];

    for (const [key, value] of Object.entries(envVars)) {
      lines.push(`${key}=${value}`);
    }

    return lines.join('\n');
  }
}
